// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsxM-9XIWIZxxnCvyjR2T7frKx_YNOzzY',
    appId: '1:743745805132:web:31ee5c2370caee58078de9',
    messagingSenderId: '743745805132',
    projectId: 'coffee-shop-fe348',
    authDomain: 'coffee-shop-fe348.firebaseapp.com',
    storageBucket: 'coffee-shop-fe348.firebasestorage.app',
    measurementId: 'G-G2LFS7DPVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC88SNwHX0Ehz9m_VUdFMh70IqNPK0_Qo4',
    appId: '1:743745805132:android:50d6e7017814f653078de9',
    messagingSenderId: '743745805132',
    projectId: 'coffee-shop-fe348',
    storageBucket: 'coffee-shop-fe348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8CigJoI3ifn85g8bT7IW_QD01xZfTss',
    appId: '1:743745805132:ios:2fc66f4d8d4de324078de9',
    messagingSenderId: '743745805132',
    projectId: 'coffee-shop-fe348',
    storageBucket: 'coffee-shop-fe348.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8CigJoI3ifn85g8bT7IW_QD01xZfTss',
    appId: '1:743745805132:ios:2fc66f4d8d4de324078de9',
    messagingSenderId: '743745805132',
    projectId: 'coffee-shop-fe348',
    storageBucket: 'coffee-shop-fe348.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsxM-9XIWIZxxnCvyjR2T7frKx_YNOzzY',
    appId: '1:743745805132:web:7f6dc940b3b70737078de9',
    messagingSenderId: '743745805132',
    projectId: 'coffee-shop-fe348',
    authDomain: 'coffee-shop-fe348.firebaseapp.com',
    storageBucket: 'coffee-shop-fe348.firebasestorage.app',
    measurementId: 'G-NE3K7VF437',
  );
}
